const Koa = require('koa')
const KoaBody = require('koa-body')
const cors = require('@koa/cors')
const Auth = require('./app/api/v1/auth')
const test = require('./app/api/v1/test')
const y = require('./app/api/v1/y')
const app = new Koa()

app.use(cors())
app.use(KoaBody())
app.use(Auth.routes())
app.use(y.routes())
app.use(test.routes())
app.listen(3000)